name: cooksmart
description: A Flutter app to find recipes and meal planning
publish_to: 'none' # Remove this line if you are publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0 # Untuk melakukan request API
  provider: ^6.0.5 # Untuk state management
  sqflite: ^2.0.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
